
server:  port: 8083

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2000